{{- if and (.Values.config.typha.enabled) (not .Values.pspDisabled) }}
---
apiVersion: {{ include "podsecuritypolicyversion" .}}
kind: PodSecurityPolicy
metadata:
  name: gardener.kube-system.typha-cpa
spec:
  volumes:
  - projected
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: MustRunAs
    ranges:
    - min: 1
      max: 65534
  fsGroup:
    rule: MustRunAs
    ranges:
    - min: 1
      max: 65534
{{- end }}
