{{- if not .Values.pspDisabled }}
---
apiVersion: {{ include "podsecuritypolicyversion" .}}
kind: PodSecurityPolicy
metadata:
  name: gardener.kube-system.calico
spec:
  privileged: true
  volumes:
  - hostPath
  - secret
  - projected
  hostNetwork: true
  {{- if .Values.config.monitoring.enabled }}
  hostPorts:
    - min: 9091
      max: 9091
  {{- end }}
  allowedHostPaths:
  - pathPrefix: /lib/modules
  - pathPrefix: /var/run/calico
  - pathPrefix: /var/lib/calico
  - pathPrefix: /opt/cni/bin
  - pathPrefix: /etc/cni/net.d
  - pathPrefix: /run/xtables.lock
  - pathPrefix: /var/run/nodeagent
  - pathPrefix: /usr/libexec
  - pathPrefix: /var/lib/kubelet/volumeplugins/nodeagent~uds
  - pathPrefix: /var/log/calico/cni
  - pathPrefix: /sys/fs/
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  readOnlyRootFilesystem: false
{{- end}}
