{{- if not .Values.pspDisabled }}
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  annotations:
    seccomp.security.alpha.kubernetes.io/defaultProfileName: 'runtime/default'
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'runtime/default'
  name: gardener.kube-system.calico
spec:
  privileged: true
  {{- if .Values.config.nonPrivileged }}
  allowedCapabilities:
  - NET_RAW
  - NET_ADMIN
  - NET_BIND_SERVICE
  {{- end }}
  volumes:
  - hostPath
  - secret
  - projected
  hostNetwork: true
  {{- if .Values.config.monitoring.enabled }}
  hostPorts:
    - min: 9091
      max: 9091
  {{- end }}
  allowedHostPaths:
  - pathPrefix: /lib/modules
  {{- if not .Values.config.nonPrivileged }}
  - pathPrefix: /var/run/calico
  - pathPrefix: /var/lib/calico
  {{- else }}
  - pathPrefix: /var/run
  - pathPrefix: /var/lib
  - pathPrefix: /var/log
  {{- end }}
  - pathPrefix: /opt/cni/bin
  - pathPrefix: /etc/cni/net.d
  - pathPrefix: /run/xtables.lock
  - pathPrefix: /var/run/nodeagent
  - pathPrefix: /usr/libexec
  - pathPrefix: /var/lib/kubelet/volumeplugins/nodeagent~uds
  - pathPrefix: /var/log/calico/cni
  - pathPrefix: /sys/fs/
  - pathPrefix: /proc
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  readOnlyRootFilesystem: false
{{- end }}
