{{- if not .Values.pspDisabled }}
---
apiVersion: {{ include "podsecuritypolicyversion" .}}
kind: PodSecurityPolicy
metadata:
  name: gardener.kube-system.calico-node-cpva
spec:
  volumes:
  - configMap
  - projected
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: MustRunAs
    ranges:
    - min: 1
      max: 65534
  fsGroup:
    rule: MustRunAs
    ranges:
    - min: 1
      max: 65534
{{- end }}
