{{- if and (.Values.config.typha.enabled) (not .Values.pspDisabled) }}
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  annotations:
    seccomp.security.alpha.kubernetes.io/defaultProfileName: 'runtime/default'
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'runtime/default'
  name: gardener.kube-system.typha-cpva
spec:
  volumes:
  - configMap
  - projected
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: MustRunAs
    ranges:
    - min: 1
      max: 65534
  fsGroup:
    rule: MustRunAs
    ranges:
    - min: 1
      max: 65534
{{- end }}
